// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// wseq_cpp
SEXP wseq_cpp(const SEXP& x, int i, int size, bool clamped);
RcppExport SEXP _xtstools_wseq_cpp(SEXP xSEXP, SEXP iSEXP, SEXP sizeSEXP, SEXP clampedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const SEXP& >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type i(iSEXP);
    Rcpp::traits::input_parameter< int >::type size(sizeSEXP);
    Rcpp::traits::input_parameter< bool >::type clamped(clampedSEXP);
    rcpp_result_gen = Rcpp::wrap(wseq_cpp(x, i, size, clamped));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_xtstools_wseq_cpp", (DL_FUNC) &_xtstools_wseq_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_xtstools(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
