# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

wseq_cpp <- function(x, i, size, clamped = TRUE) {
    .Call(`_xtstools_wseq_cpp`, x, i, size, clamped)
}

